# -*- coding: utf-8 -*-
"""DiabetesDetectionUsingNeuralNetwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u60g0XyYVcZdV9hBtRXICV_AiNHwR94Q
"""

from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json

from google.colab import files
uploaded = files.upload()

dataset = loadtxt('pima-indians-diabetes.csv', delimiter = ',')
x = dataset[:, :8]
y = dataset[:, 8]

model = Sequential()
model.add(Dense(12, input_dim = 8,activation='relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

model.compile(loss = 'binary_crossentropy', optimizer= 'adam',metrics = ['accuracy'])
model.fit(x, y, epochs = 400, batch_size = 10)
_,accuracy = model.evaluate(x,y)
print('Accuaracy = %.2f' % (accuracy*100))

model_json = model.to_json()
with open ("model.json", "w") as json_file:
  json_file.write(model_json)
model.save_weights("model.h5")
print("Saved model to Disk")

"""Testing"""

dataset = loadtxt('pima-indians-diabetes.csv', delimiter = ',')
x = dataset[:, :8]
y = dataset[:, 8]

json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("model.h5")
print("Loaded model from Disk")

predictions=model.predict(x) 
for i in range(5,10):
	print('%s => %d (expected %d)' % (x[i].tolist(), predictions[i], y[i]))

